# Server Configuration
server.port=${PORT:8080}

# Application Name
spring.application.name=Finastrax


# Active Profile
spring.profiles.active=${ENV:dev}

jwt.secret=finastrax-secret-key-change-this-later
jwt.expiration=86400000


# ===============================
# JPA / Hibernate Common Settings
# ===============================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false

spring.jpa.properties.hibernate.format_sql=false

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# Hibernate Batch Configuration
spring.jpa.properties.hibernate.jdbc.batch_size=500
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true



# Performance Monitoring
spring.jpa.properties.hibernate.generate_statistics=false


# ===============================
# File Upload Configuration
# ===============================

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB


# ===============================
# Logging
# ===============================

logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.orm.jdbc.bind=OFF