# ===============================
# Production Database
# ===============================
spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway


spring.datasource.username=root

spring.datasource.password=QhdWrByDiUtniwodbrcIIJiaInayfaQa

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# Production Logging

logging.level.root=WARN
logging.level.org.hibernate.SQL=WARN